### ISSUE TITLE
Keyboard switcher applet changes width on hover

### ISSUE THREAD

**Issue by mikehaertl** [linuxmint/cinnamon-spices-themes#195]
I'm using the keyboard toggle applet together with the Void theme. When I hover the the flag, the width of the icon changes and makes the complete task bar "jump" to the right.

See the screenshot below. Top bar is without hover. The bottom bar is the same when hovering the German flag.

![language_switcher_jumps](https://user-images.githubusercontent.com/675062/27822113-d5f46154-60a4-11e7-86f4-a892d1864680.png)

I've observed this only with the Void theme, that's why I'm reporting this here. If there's a better place please let me know and I will move the issue.

**Comment by brownsr** [comment]
This is just the right place to report it, thanks :-)

**Comment by mikehaertl** [comment]
@brownsr Any news here? Anything I can do to help?

**Comment by mikehaertl** [comment]
Ok, I've tried myself, but all I could find out is this: When I remove [this block](https://github.com/linuxmint/cinnamon-spices-themes/blob/master/Void/files/Void/cinnamon/cinnamon.css#L1882) in the `cinammon.css`:

```css
.applet-box:hover {
    color: #000;
    border-radius: 10px 10px 10px 10px;
    background-gradient-direction: vertical;
    background-gradient-start: rgba(55,55,55,0.05);
    background-gradient-end: rgba(55,55,55,0.21);
}
```
then the hover effect for all applet icons is gone - **except** for the language switcher! So it seems, like this icon is styled somewhere else and handled different from all the others.

@brownsr Does this ring a bell for you? Do you maybe have a pointer where I could look? I'd really try to help and provide a PR but I'm a bit lost as theming is not really documented very well it seems.

**Comment by mikehaertl** [comment]
Here's more: I've removed the `padding: 0 2px;` [this block](https://github.com/linuxmint/cinnamon-spices-themes/blob/master/Void/files/Void/cinnamon/cinnamon.css#L300), and now the issue is gone! But I don't know if this has any side effects:

```css
.panel-status-button:hover,
.panel-button:hover {
    padding: 0 2px;
    color: black;
    border-radius: 10px 10px 10px 10px;
    background-gradient-direction: vertical;
    background-gradient-start: rgba(55,55,55,0.11);
    background-gradient-end: rgba(55,55,55,0.41);
    transition-duration: 100;
}
```
